"""empty message

Revision ID: 8b4cff954d91
Revises: 
Create Date: 2020-11-23 09:37:20.264562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8b4cff954d91'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('board_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=255), nullable=False),
    sa.Column('user_name', sa.String(length=255), nullable=True),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk__comments__parent_id__comments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__comments'))
    )
    op.create_index(op.f('ix__comments__board_id'), 'comments', ['board_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__comments__board_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
