version: '3.1'

services:
  db:
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file:
      - .env
    networks:
      - common

  app:
    ports:
      - 8001:8000
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - common
    env_file:
      - .env
    environment:
      - ENV=TEST
      - DB_HOST=comment-board_db_1

networks:
  common:
     external: true